name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main
jobs:
  deploy_to_hosting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Firebase CLI (standalone)
        run: curl -sL https://firebase.tools | bash

      - name: Setup service account
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ABELION_AI_466122 }}' > $RUNNER_TEMP/gcp.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/gcp.json" >> $GITHUB_ENV

      - name: Deploy Hosting
        run: |
          cd frontend
          firebase deploy --only hosting --project abelion-ai-466122 --non-interactive
